# yamllint disable rule:line-length
# yamllint disable rule:braces

name: Code Analysis

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Static code analysis with PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - "7.4"

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-${{ matrix.php-version }}-${{ hashFiles('composer.*') }}
          restore-keys: |
            composer-${{ matrix.php-version }}-
            composer-

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress

      - name: Run Psalm
        run: |
          php vendor/bin/psalm --output-format=github --long-progress --php-version=${{ matrix.php-version }}
